# Site settings
title: 星星笑语的世界
SEOTitle: 星星笑语的个人博客
header-img: img/home_background.png
email: xujiafeng_31415926@163.com
description: "关注于Android、算法的个人博客"
keyword: "星星笑语，Android，算法"
url: "http://xingxingxiaoyu.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/xingxingxiaoyu/xingxingxiaoyu.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "做一个好人！"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
github_username:    xingxingxiaoyu



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
# disqus_username: https-kaolamobile-github-io

# Duoshuo settings
# duoshuo_username: KaolaMobile
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
#ga_track_id: 'UA-114840609-1'           # Format: UA-xxxxxx-xx
#ga_domain: kaolamobile.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "星星笑语"
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Friends
friends: [
    {
        title: "xingxingxiaoyu",
        href: "https://github.com/xingxingxiaoyu"
    },
    {
        title: "KaolaMobile",
        href: "https://kaolamobile.github.io"
    }
]
